version: "3.8"

services:

  webserver:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - users_api
    networks:
      - prod_network

  users_api:
    build:
      context: ./APIS
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.15"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    expose:
      - "3000-3004:3000"
    volumes:
      - ./APIS/users/:/usr/usersAPI/
    depends_on:
      - db
    networks:
      - prod_network

  db:
    image: postgres
    shm_size: 128mb
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 2GB
        reservations:
          cpus: "0.1"
          memory: 1GB
    ports:
      - 5432:5432
    volumes:
      - ./pgdata_prod/users:/var/lib/postgresql/data
    env_file:
      - ./.env.prod
    networks:
      - prod_network
  


networks:
  prod_network:
    driver: bridge
