version: "3.8"

services:

  webserver:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - users_api
    networks:
      - dev_network

  users_api:
    build:
      context: ./APIS
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.15"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    ports:
      - "3000-3004:3000"
    volumes:
      - ./APIS/users/:/usr/usersAPI/
    depends_on:
      - db
    networks:
      - dev_network

  db:
    image: postgres
    shm_size: 128mb
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 2GB
        reservations:
          cpus: "0.1"
          memory: 1GB
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/users:/var/lib/postgresql/data
    networks:
      - dev_network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: distri_pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dani@dani.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
